import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import "./globals.css";
import RootProvider from "@/providers/RootProvider";

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Generate With AI ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider >
        {children}
        </RootProvider>
      </body>
    </html>
  );
}
